POST http://localhost:3000/auth/login
Content-Type: application/json

{
	"email": "patner1@user.com",
	"password": "123456"
}

###

POST http://localhost:3000/partners
Content-Type: application/json

{
	"name": "Partner 13",
    "company_name": "Company 1",
	"email": "patner212@user.com",
	"password": "123456"
}

###

POST http://localhost:3000/customers
Content-Type: application/json

{
	"name": "Partner 1",
	"email": "patner32w1@user.com",
	"password": "123456",
    "address": "Rua das flores, 100, São Paulo, SP",
    "phone": "11999999999"
} 

### Criacao do evento pelo parceiro

POST http://localhost:3000/partners/events
Content-Type: application/json

{
	"name": "Partner 1",
    "description": "Show do luiz",
    "date": "2026-01-01:T00:00:00",
    "location": "Rua das flores, 100, São Paulo, SP"
}

### Listagem dos eventos
GET http://localhost:3000/events

### Listagem do evento
GET http://localhost:3000/events/2

### Listagem dos eventos pelo parceiro
GET http://localhost:3000/partners/events

### Listagem do evento pelo parceiro
GET http://localhost:3000/partners/events/2